"""
HDB ResaleXAI — FastAPI Backend
Load all artefacts at startup into a shared AppState object.
All route modules import from this state — zero per-request cold starts.
"""

from contextlib import asynccontextmanager
from pathlib import Path
import os

import json
import joblib
import pandas as pd
import lime.lime_tabular
from dotenv import load_dotenv
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

# ── Paths ─────────────────────────────────────────────────────────
BACKEND_DIR = Path(__file__).parent
REPO_ROOT = BACKEND_DIR.parent
load_dotenv(REPO_ROOT / ".env")
load_dotenv(BACKEND_DIR / ".env", override=True)
_art = os.environ.get("PROPERTYLENS_ARTIFACTS_DIR", "").strip()
_feat = os.environ.get("PROPERTYLENS_FEATURE_LAYER_OUTPUTS", "").strip()
ARTIFACTS_ROOT = Path(_art) if _art else REPO_ROOT / "data" / "artifacts"
FEATURE_LAYER_OUTPUTS = (
    Path(_feat) if _feat else REPO_ROOT / "data" / "feature_data" / "02_feature_layer" / "training" / "outputs"
)
_ft_csv_env = os.environ.get("PROPERTYLENS_FEATURE_TABLE_CSV", "").strip()
FEATURE_TABLE_CSV_RESOLVED: Path | None = None
if _ft_csv_env:
    _p_ft = Path(_ft_csv_env)
    FEATURE_TABLE_CSV_RESOLVED = (
        _p_ft.resolve() if _p_ft.is_absolute() else (REPO_ROOT / _p_ft).resolve()
    )
HYBRID_XAI_DIR = ARTIFACTS_ROOT / "hybrid_xai"
# Legacy alias for analytics (parquet / trend sources)
DATA_PROCESSED = ARTIFACTS_ROOT


# ── Shared app state ──────────────────────────────────────────────
class AppState:
    hybrid_bundle = None
    xgb_model = None  # HybridPredictWrapper — LIME / predict.predict compatibility
    lime_explainer = None
    cbr_tree = None
    cbr_scaler = None
    cbr_df = None
    feature_cols = None
    cbr_feature_cols = None
    global_shap = None
    global_shap_by_cluster = None
    rules = None
    hdb_df = None  # loaded lazily for trends endpoint
    model_meta = None  # hybrid_cluster_meta.json loaded at startup
    cached_town_summary = None  # computed once at startup
    cached_trends = None  # computed once at startup


state = AppState()


# ── Lifespan: load artefacts once at startup ──────────────────────
@asynccontextmanager
async def lifespan(app: FastAPI):
    from backend.hybrid_inference import HybridPredictWrapper, configure, load_bundle

    print("Loading artefacts...")
    print(f"   Artefacts: {ARTIFACTS_ROOT}")
    print(f"   Hybrid XAI: {HYBRID_XAI_DIR}")
    print(f"   Feature tables: {FEATURE_LAYER_OUTPUTS}")
    if FEATURE_TABLE_CSV_RESOLVED:
        print(f"   Feature table (pinned): {FEATURE_TABLE_CSV_RESOLVED}")
    else:
        print("   Feature table: latest hdb_feature_table_*.csv under outputs (set PROPERTYLENS_FEATURE_TABLE_CSV to pin)")

    configure(ARTIFACTS_ROOT, FEATURE_LAYER_OUTPUTS, feature_table_csv=FEATURE_TABLE_CSV_RESOLVED)

    bundle = load_bundle()
    state.hybrid_bundle = bundle
    state.feature_cols = list(bundle["feature_columns"])
    state.xgb_model = HybridPredictWrapper(bundle)

    state.cbr_tree = joblib.load(HYBRID_XAI_DIR / "cbr_index.joblib")
    state.cbr_scaler = joblib.load(HYBRID_XAI_DIR / "cbr_scaler.joblib")
    state.cbr_df = pd.read_parquet(HYBRID_XAI_DIR / "cbr_training_data.parquet")

    with open(HYBRID_XAI_DIR / "cbr_features.json") as f:
        state.cbr_feature_cols = json.load(f)

    with open(HYBRID_XAI_DIR / "global_shap_cache.json") as f:
        state.global_shap = json.load(f)

    # Optional: per-cluster global SHAP importance + baselines for Analyst view.
    # Generated by notebooks/04_xai_layer/04_hybrid_xai_train.ipynb.
    by_cluster_path = HYBRID_XAI_DIR / "global_shap_by_cluster.json"
    if by_cluster_path.exists():
        with open(by_cluster_path) as f:
            state.global_shap_by_cluster = json.load(f)

    with open(HYBRID_XAI_DIR / "rules.json") as f:
        state.rules = json.load(f)

    lime_data = joblib.load(HYBRID_XAI_DIR / "lime_training_data.joblib")
    state.lime_explainer = lime.lime_tabular.LimeTabularExplainer(
        training_data=lime_data["training_data"],
        feature_names=lime_data["feature_names"],
        mode="regression",
        random_state=42,
    )

    meta_path = ARTIFACTS_ROOT / "hybrid_cluster_meta.json"
    if not meta_path.exists():
        raise RuntimeError(
            f"Required model metadata missing: {meta_path}. "
            "Run 03_ml_layer_hybrid/02_hybrid_ensemble.ipynb to regenerate."
        )
    with open(meta_path) as f:
        state.model_meta = json.load(f)
    if not state.model_meta.get("test_metrics"):
        raise RuntimeError(
            f"{meta_path} is missing 'test_metrics'. Retrain the hybrid ensemble."
        )

    print("✅ Hybrid cluster artefacts loaded")
    print(f"   Features: {len(state.feature_cols)}")
    print(f"   CBR cases: {len(state.cbr_df):,}")
    try:
        from backend.db import SessionLocal, init_db
        from backend.auth_routes import ensure_demo_user

        init_db()
        _sess = SessionLocal()
        try:
            ensure_demo_user(_sess)
        finally:
            _sess.close()
        print("✅ User history DB initialized (SQLite / DATABASE_URL)")
    except Exception as e:
        print(f"⚠️ User history DB init failed: {e}")
    yield
    print("Shutting down")


# ── App ───────────────────────────────────────────────────────────
app = FastAPI(
    title="PropertyLens API",
    description="Explainable HDB resale price prediction (PropertyLens)",
    version="1.0.0",
    lifespan=lifespan,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


from starlette.middleware.base import BaseHTTPMiddleware  # noqa: E402
from starlette.requests import Request  # noqa: E402


class CacheControlMiddleware(BaseHTTPMiddleware):
    CACHEABLE_PREFIXES = ("/api/analytics/", "/api/model-meta", "/api/rules", "/api/nearby")

    async def dispatch(self, request: Request, call_next):
        response = await call_next(request)
        if any(request.url.path.startswith(p) for p in self.CACHEABLE_PREFIXES):
            response.headers["Cache-Control"] = "public, max-age=3600"
        return response


app.add_middleware(CacheControlMiddleware)


# ── Import and register routers ───────────────────────────────────
from backend.predict import router as predict_router  # noqa: E402
from backend.cbr import router as cbr_router  # noqa: E402
from backend.analytics import router as analytics_router  # noqa: E402
from backend.counterfactual import router as cf_router  # noqa: E402
from backend.chat import router as chat_router  # noqa: E402
from backend.location import router as location_router  # noqa: E402
from backend.history import router as history_router  # noqa: E402
from backend.wishlist import router as wishlist_router  # noqa: E402
from backend.auth_routes import router as auth_router  # noqa: E402
from backend.constraints import validate_listing, ValidateRequest  # noqa: E402

app.include_router(predict_router, prefix="/api")
app.include_router(cbr_router, prefix="/api")
app.include_router(analytics_router, prefix="/api")
app.include_router(cf_router, prefix="/api")
app.include_router(chat_router, prefix="/api")
app.include_router(location_router, prefix="/api")
app.include_router(history_router, prefix="/api")
app.include_router(wishlist_router, prefix="/api")
app.include_router(auth_router, prefix="/api")


@app.post("/api/validate-listing")
def validate_listing_endpoint(req: ValidateRequest):
    return validate_listing(req)


# ── Policy KB endpoint ────────────────────────────────────────────

_POLICY_META = [
    {"name": "HDB Lease Buyback 2024",     "year": 2024, "impact": "positive"},
    {"name": "ABSD 30% Foreigners 2022",   "year": 2022, "impact": "negative"},
    {"name": "Post-COVID Boom 2021-2022",   "year": 2021, "impact": "positive"},
    {"name": "COVID Restriction 2020",     "year": 2020, "impact": "mixed"},
    {"name": "LTV Tightening 2018",        "year": 2018, "impact": "negative"},
    {"name": "ABSD Increase 2013",         "year": 2013, "impact": "negative"},
]

_POLICY_EXPLANATIONS = {
    "ABSD Increase 2013": (
        "The 2013 ABSD increase raised stamp duties for second and third property purchases, "
        "cooling speculative investment demand across Singapore including {town}."
    ),
    "LTV Tightening 2018": (
        "The 2018 Loan-to-Value tightening reduced the maximum mortgage loan buyers could take, "
        "constraining purchasing power and moderating prices in {town}."
    ),
    "COVID Restriction 2020": (
        "COVID-19 restrictions in 2020 initially disrupted viewings and transactions in {town}, "
        "though pent-up demand later drove a sharp recovery."
    ),
    "Post-COVID Boom 2021-2022": (
        "The post-COVID demand surge in 2021-2022 drove significant price growth in {town} "
        "as buyers re-entered the market with strong intent."
    ),
    "ABSD 30% Foreigners 2022": (
        "The 2022 cooling measures — raising ABSD for foreigners to 30% — reduced speculative demand "
        "and caused a short-term price stabilisation in {town}."
    ),
    "HDB Lease Buyback 2024": (
        "The 2024 Lease Buyback Scheme expansion increased demand for resale flats in mature estates "
        "like {town} by giving elderly owners more liquidity options."
    ),
}


@app.get("/api/kb/policy-impact/{town}")
def get_policy_impact(town: str):
    """Return all policies that affected this town, sorted by year descending."""
    town_upper = town.upper()
    town_title = town.title()

    # Try Neo4j first; fall back to hardcoded list
    kb_source = "hardcoded"
    confirmed_names: set[str] | None = None

    try:
        import os
        from neo4j import GraphDatabase
        uri  = os.environ.get("NEO4J_URI", "bolt://localhost:7687")
        user = os.environ.get("NEO4J_USER", "neo4j")
        pwd  = os.environ.get("NEO4J_PASSWORD", "password")
        driver = GraphDatabase.driver(uri, auth=(user, pwd))
        with driver.session() as session:
            result = session.run(
                "MATCH (p:Policy)-[:AFFECTED]->(t:Town {name: $town}) "
                "RETURN p.name AS name",
                town=town_upper,
            )
            confirmed_names = {r["name"] for r in result}
        driver.close()
        if confirmed_names:
            kb_source = "neo4j"
    except Exception:
        pass  # graceful fallback

    policies = []
    for meta in _POLICY_META:
        if confirmed_names is not None and meta["name"] not in confirmed_names:
            continue
        explanation = _POLICY_EXPLANATIONS.get(meta["name"], "")
        policies.append({
            "name":        meta["name"],
            "year":        meta["year"],
            "impact":      meta["impact"],
            "explanation": explanation.format(town=town_title),
        })

    positive = sum(1 for p in policies if p["impact"] == "positive")
    negative = sum(1 for p in policies if p["impact"] == "negative")
    if positive > negative:
        net_sentiment = "cautiously positive"
    elif negative > positive:
        net_sentiment = "policy headwinds present"
    else:
        net_sentiment = "mixed policy environment"

    return {
        "town":          town_upper,
        "policies":      policies,
        "net_sentiment": net_sentiment,
        "kb_source":     kb_source,
    }


@app.get("/api/model-meta")
def model_meta():
    """Model metadata and test-set metrics for frontend display."""
    meta = state.model_meta
    test = meta["test_metrics"]
    return {
        "model_name": meta["model_name"],
        "model_type": meta["model_type"],
        "base_models": meta.get("base_models", []),
        "meta_learner": meta.get("meta_learner"),
        "n_clusters": meta["n_clusters"],
        "n_features": meta.get("n_features", len(state.feature_cols)),
        "r2": test["r2"],
        "rmse": test["rmse"],
        "mape_pct": test["mape_pct"],
        "mae": test["mae"],
        "train_size": meta["train_size"],
        "test_size": meta["test_size"],
        "total_transactions": meta["train_size"] + meta.get("val_size", 0) + meta["test_size"],
    }


@app.get("/health")
def health():
    meta = state.model_meta
    test = meta["test_metrics"]
    return {
        "status": "ok",
        "model": meta["model_name"],
        "artifacts_dir": str(ARTIFACTS_ROOT),
        "rmse": test["rmse"],
        "r2": test["r2"],
        "mape_pct": test["mape_pct"],
        "features": len(state.feature_cols),
        "normalised_model_loaded": False,
        "ensemble_mode": True,
        "ensemble_type": meta["model_type"],
    }

